<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DebugType>embedded</DebugType>
    <AssemblyName>dev-oidc-toolkit</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyVersion Condition=" '$(VERSION)' == '' ">0.0.0.0</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VERSION)' != '' ">$(VERSION)</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.3" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.2.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.2.0" />
    <PackageReference Include="System.Linq.Async" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <EmbeddedResource Include="Documentation/**/*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="config.json" CopyToPublishDirectory="Never" />
    <Content Update="dist/**/*" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
